

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  shutdown: graceful

spring:
  application:
    name: musinsa-exam
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:musinsa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML

springdoc:
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    disable-swagger-default-url: false
    syntax-highlight:
      activated: false
    deep-linking: false
    enabled: true
  api-docs:
    enabled: true
  model-and-view-allowed: false
  cache:
    disabled: true
  pre-loading-enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  enable-spring-security: false