

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  shutdown: graceful

spring:
  application:
    name: musinsa-exam
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:musinsa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
